#!/usr/bin/env python3
import sys
import os

# Add the src directory to the system path
sys.path.append(0, os.path.join(os.path.dirname(__file__), 'src'))

from logic import main

if __name__ == "__main__":
    main()